    version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo "Setting up custom environment..."
      - amazon-linux-extras enable python3.8
      - yum install -y python3.8 zip
  build:
    commands:
      - echo "This is the build phase... Zipping my lambda function"
      - zip -r deployment_package.zip lambda_function.py
  post_build:
    commands:
    - echo "Deploying to the Lambda"
    - aws lambda update-function-code --function-name  hello_world --zip-file fileb://deployment_package.zip

artifacts:
  type: zip
  paths:
    - '*'
