version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"

phases:
  pre_build:
    commands:
      - echo "Setting up custom environment..."
      # Install Python 3.8
      - apt-get update
      - apt-get install -y python3.8
      # Install any other dependencies you might need
      # Replace 'your_aws_region' with the AWS region you are using for AWS CLI commands

  build:
    commands:
      - echo "This is build phase... Zipping my lambda function"
      - zip -r deployment_package.zip lambda_function.py

artifacts:
  files:
    - deployment_package.zip
